version: "3"

services:
  webhook:
    container_name: test-webhook
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=${PORT:-15201}
    image: catcatio/test-webhook
    working_dir: /usr/app
    ports:
      - "15201:15201"
    volumes:
      - .:/usr/app
    command: npm run dev:docker
